ethiopian_medical_data:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: "{{ env_var('DB_USER', 'postgres') }}"
      password: "{{ env_var('DB_PASSWORD', 'password') }}"
      dbname: ethiopian_medical_data
      schema: public
      threads: 4
      keepalives_idle: 0
      search_path: public
      role: null
      sslmode: prefer
    prod:
      type: postgres
      host: "{{ env_var('DB_HOST', 'localhost') }}"
      port: "{{ env_var('DB_PORT', '5432') }}"
      user: "{{ env_var('DB_USER', 'postgres') }}"
      password: "{{ env_var('DB_PASSWORD', 'password') }}"
      dbname: "{{ env_var('DB_NAME', 'ethiopian_medical_data') }}"
      schema: public
      threads: 8
      keepalives_idle: 0
      search_path: public
      role: null
      sslmode: require 